language: erlang
otp_release: 17.3
install:
  # - sh -c "if ! [ -z '$TRAVIS_TAG' ]; then sudo apt-get install ruby-dev rubygems; gem install fpm; fi"
  # - sudo apt-get install ruby-dev rubygems
  - gem install fpm
script:
  # - sh -c "echo "TRAVIS_TAG=[$TRAVIS_TAG]" && if [ -z '$TRAVIS_TAG' ]; then make tests; else make tests rel; fi"
  - echo "TRAVIS_TAG=[$TRAVIS_TAG]"
  - uname -a
  - make tests
after_success:
  - make rel
notifications:
  email:
  - baden.i.ua@gmail.com
services:
  - mongodb
deploy:
  provider: releases
  api_key:
    secure: Tei4LYVDPenLotEavQsPzcNYAqpWpx15mpmLf/YqB2G/NfWxSCbpHIvlYw0MrlcLr/lZM8qFNIkJGv+mLZZtIzxiJohxuCHZp9/qh8e2BiYnjiylfM9XhNxgStdi8wcwAiBXKYpNwA9IJn/mx3DNyNGID1ba4v57ztd+qZiWEvE=
  file:
    - deploy/navicc_release_${TRAVIS_TAG}.deb
    - _rel/navicc_release/navicc_release-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    repo: baden/navicc
    all_branches: true
    tags: true
before_deploy:
  - make deb
  - ls deploy
after_deploy: "echo 'after deploy'"
