language: erlang
otp_release: 17.3
before_install:
- echo $TRAVIS_BRANCH
- echo $TRAVIS_TAG
- echo $env.CI_DEPLOY_USERNAME
install:
- gem install fpm
script:
- echo "TRAVIS_TAG=[$TRAVIS_TAG]"
- uname -a
- make tests
after_success:
- make rel
notifications:
  email:
  - baden.i.ua@gmail.com
services:
- mongodb
before_deploy:
- make deb
- ls deploy
deploy:
  provider: releases
  api_key:
    secure: mify/tTT8pJG9zIoS7AglSKhR89LbzQHoS8hsgUljn4BR0hqJUymWQvxJlZTJ//T15dlQ/38AP6fNiG6qu2pdpQdrQZRNrBF3ZvZyrbltvqDyMCAMAYGxkFvBa9SVCAwVvB/VyByq+YM0v1Zrq8in5xv5LDunWXzKtRwmzOG4k8=
  file: deploy/navicc-server_${TRAVIS_TAG}_amd64.deb
  on:
    repo: baden/navicc
after_deploy: echo 'after deploy'
