language: erlang
otp_release: 20.0
before_install:
- echo $TRAVIS_BRANCH
- echo $TRAVIS_TAG
- echo $TRAVIS_COMMIT
- echo $env.CI_DEPLOY_USERNAME
install:
- gem install fpm
script:
- echo "TRAVIS_TAG=[$TRAVIS_TAG]"
- uname -a
- make elvis tests
after_success:
- make rel
notifications:
  email:
  - baden.i.ua@gmail.com
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_deploy:
- make tarball
- ls deploy
- export TAR_FILE=$(ls deploy/*.tar.gz)
- echo "TAR_FILE=${TAR_FILE}"
deploy:
  provider: releases
  api_key:
    secure: mify/tTT8pJG9zIoS7AglSKhR89LbzQHoS8hsgUljn4BR0hqJUymWQvxJlZTJ//T15dlQ/38AP6fNiG6qu2pdpQdrQZRNrBF3ZvZyrbltvqDyMCAMAYGxkFvBa9SVCAwVvB/VyByq+YM0v1Zrq8in5xv5LDunWXzKtRwmzOG4k8=
  # file: "${TAR_FILE}"
  file: deploy/*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: baden/navicc
    all_branches: true
    tags: false
after_deploy: echo 'after deploy'
