version: '2'

services:
  # redis:
  #   image: redis

  mongo:
    image: mongo
    # ports:
    #   - "27017:27017"

  app:
    # image: baden-navicc
    build: .
    tty: true
    links:
      - "mongo:mongo"
    depends_on:
      - mongo
    # entrypoint:
    #   - _rel/navicc-server/bin/navicc-server
    #   - console
    # expose:
    #   - "8981"
    #   - "8982"
    #   - "8983"
    ports:
      - "8981:8981"
      - "8982:8982"
      - "8983:8983"

  # bash:
  #   image: baden/debian
  #   links:
  #     - "mongo:mongo"
  #     - "app:app"
  #   ports:
  #     - "8000:8000"
  #   # expose:
  #   #   - "8000"
  #
  # erlang:
  #   image: baden/erlang
  #   links:
  #     - "mongo:mongo"
  #     - "app:app"
