#!/bin/sh

APP=navicc-server
USER=navicc
LOG=/var/log/$APP
export HOME=/var/lib/$APP

export NL="
"
export RELX_REPLACE_OS_VARS=1   # Expand vars in config
export RUNNER_LOG_DIR=$LOG
cp -f /etc/$APP/vm.args $HOME/vm.args
cp -f /etc/$APP/sys.config $HOME/sys.config
export VMARGS_PATH=$HOME/vm.args
export CONFIG_PATH=$HOME/sys.config
# export VMARGS_PATH=/etc/$APP/vm.args
# export CONFIG_PATH=/etc/$APP/sys.config

# save hostname
export FQDN=$(hostname -f)

# Escape spaces and quotes, because shell is revolting.
for arg in "$@" ; do
	# Escape quotes in parameters, so that they're passed through cleanly.
	arg=$(sed -e 's/"/\\"/g' <<-END
		$arg
		END
	)
	CMDLINE="${CMDLINE} \"${arg}\""
done

cd /var/lib/$APP

# mkdir -m /usr/lib/navicc-server/stats

SCRIPT=`basename $0`

if [ `id -u` = `id -u ${USER}` -a "$SCRIPT" = "${APP}" ] ; then
	echo "CMDLINE: ${CMDLINE}"
	echo "SCRIPTNAME: ${SCRIPT}"
	# echo "Exec: `dirname $0`/$APP $@"
	/usr/lib/${APP}/bin/${APP} "$@"  > "${LOG}/startup_log" 2> "${LOG}/startup_err"
	# echo "/usr/lib/${APP}/bin/${APP} \"$@\"  > \"${LOG}/startup_log\" 2> \"${LOG}/startup_err\""
elif [ `id -u` = 0 ] ; then
	echo "Run as ${USER}:"
	su ${USER} -s /bin/sh -c "/usr/lib/${APP}/bin/${SCRIPT} ${CMDLINE}"
	# echo "su ${USER} -s /bin/sh -c \"/usr/lib/${APP}/bin/${SCRIPT} ${CMDLINE}\""
else
	# /usr/lib/$APP/bin/$APP
	echo
	echo "Only root or ${USER} should run ${SCRIPT}"
	echo
	exit 1
fi

# exec `dirname $0`/$APP $@

exit 0

# Escape spaces and quotes, because shell is revolting.
for arg in "$@" ; do
	# Escape quotes in parameters, so that they're passed through cleanly.
	arg=$(sed -e 's/"/\\"/g' <<-END
		$arg
		END
	)
	CMDLINE="${CMDLINE} \"${arg}\""
done

cd /var/lib/rabbitmq

SCRIPT=`basename $0`

if [ `id -u` = `id -u rabbitmq` -a "$SCRIPT" = "rabbitmq-server" ] ; then
    /usr/lib/rabbitmq/bin/rabbitmq-server "$@"  > "/var/log/rabbitmq/startup_log" 2> "/var/log/rabbitmq/startup_err"
elif [ `id -u` = `id -u rabbitmq` -o "$SCRIPT" = "rabbitmq-plugins" ] ; then
    if [ -f $PWD/.erlang.cookie ] ; then
        export HOME=.
    fi
    /usr/lib/rabbitmq/bin/${SCRIPT} "$@"
elif [ `id -u` = 0 ] ; then
    su rabbitmq -s /bin/sh -c "/usr/lib/rabbitmq/bin/${SCRIPT} ${CMDLINE}"
else
    /usr/lib/rabbitmq/bin/${SCRIPT}
    echo
    echo "Only root or rabbitmq should run ${SCRIPT}"
    echo
    exit 1
fi
