#!/bin/sh

APP=navicc-server
USER=navicc
GROUP=navicc

case "$1" in
    purge)
        update-rc.d $APP remove >/dev/null
        if [ -d /var/log/$APP ]; then
                rm -r /var/log/$APP
        fi
        if [ -d /var/lib/$APP ]; then
                rm -r /var/lib/$APP
        fi
        if [ -d /etc/$APP ]; then
                rm -r /etc/$APP
        fi

        if [ -e /etc/init.d/$APP ]; then
                rm  /etc/init.d/$APP
        fi

        if getent passwd $USER >/dev/null; then
                deluser $USER
        fi
        if getent group $GROUP >/dev/null; then
                delgroup $GROUP
        fi

        update-rc.d $APP remove >/dev/null
        # if [ -d /opt/$PROJECT ]; then
        #         rm -r /opt/$PROJECT
        # fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
