#!/bin/sh

set -e

APP=navicc-server
USER=navicc
GROUP=navicc
DESCRIPTION="GPS Tracking server"

config_nginx() {
  ln -s /etc/nginx/sites-available/$APP /etc/nginx/sites-enabled/$APP
}

# create group
if ! getent group $GROUP >/dev/null; then
        addgroup --system $GROUP
fi

# create user
if ! getent passwd $USER >/dev/null; then
        adduser --ingroup $GROUP --home /var/lib/$APP --disabled-password \
		--system --shell /bin/sh \
		--gecos "$DESCRIPTION" $USER
fi

# chown -R $USER:$GROUP /opt/$PROJECT
mkdir -p /var/lib/$APP/stats
mkdir -p /var/lib/$APP/mnesia
chown -R $USER:$GROUP /var/lib/$APP
chown -R $USER:$GROUP /var/log/$APP

case "$1" in
    configure)
      config_nginx
      service nginx restart
        # if [ -x "/etc/init.d/$APP" ]; then
        #         update-rc.d $APP defaults >/dev/null || exit $?
        # fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ -x "/etc/init.d/navicc-server" ]; then
    # invoke-rc.d navicc-server stop || exit $?
    update-rc.d $APP defaults >/dev/null
    invoke-rc.d $APP start || exit $?
fi
#DEBHELPER#

exit 0
